### ISSUE TITLE
Problem with Program shutting down

### ISSUE THREAD

**Issue by Rihpsalis** [Rihpsalis/GhostGame#2] opened 2023-04-24 18:48 UTC
This is my main problem. When i start the program every thing goes as normal except my other mentioned problem #1 . But at some point after 10-30 seconds (This is not always the same) the Canvas doesn´t update anymore. The render Methods of 
```java
Player.java
Gridmap.java
``` 
are still called and work but the Canvas just stops working. This is also only happening with my biggest Gridmap (52x29 Sprites that are each scaled to 200x200 so ~2560x1440)

**Comment by armin-reichert** [comment] 2023-04-27 15:35
That might be caused by using a separate thread instead of attaching to the JavaFX application thread (see my question about the GameTimer class). If you want to shutdown JavaFX when closing your main window you can add a window close handler which calls Platform.exit().

**Closed as completed** 2023-05-08 18:54 UTC
